### ISSUE TITLE
requirement: double jeopardy

### ISSUE THREAD

**Issue by lorrainechenxi** [w531t4/Knights-of-the-Laughing-Tree#19]
There is a requirement of "In the second round, the point values are doubled from the first round (as in Jeopardy!). At the end of the game, the scores for the two rounds are added together." 

The point values didn't double in round 2. 
<img width="745" alt="Screen Shot 2019-08-14 at 6 48 03 PM" src="https://user-images.githubusercontent.com/23044116/63061713-22e7e100-bec4-11e9-9357-6f538982f5f1.png">

**Comment by w531t4** [comment]
So - do we want
Round1: (100,200,300,400,500)
Round2: (200,400,600,800,1000)?
